# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cars_catalog.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'cars_catalog.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63\x61rs_catalog.proto\x12\x04\x63\x61rs\"\x07\n\x05\x45mpty\"\xd0\x01\n\x03\x43\x61r\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\t\x12\x11\n\timage_url\x18\x04 \x01(\t\x12\x0c\n\x04year\x18\x05 \x01(\x05\x12\r\n\x05\x63olor\x18\x06 \x01(\t\x12\x14\n\x0ctransmission\x18\x07 \x01(\t\x12\x11\n\told_price\x18\x08 \x01(\t\x12\x10\n\x08\x64iscount\x18\t \x01(\t\x12\x12\n\ndrive_type\x18\n \x01(\t\x12\x0e\n\x06\x65ngine\x18\x0b \x01(\x02\x12\x11\n\tfuel_type\x18\x0c \x01(\t\".\n\x13\x43\x61rsCatalogResponse\x12\x17\n\x04\x63\x61rs\x18\x01 \x03(\x0b\x32\t.cars.Car2N\n\x12\x43\x61rsCatalogService\x12\x38\n\x0eGetCarsCatalog\x12\x0b.cars.Empty\x1a\x19.cars.CarsCatalogResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cars_catalog_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=28
  _globals['_EMPTY']._serialized_end=35
  _globals['_CAR']._serialized_start=38
  _globals['_CAR']._serialized_end=246
  _globals['_CARSCATALOGRESPONSE']._serialized_start=248
  _globals['_CARSCATALOGRESPONSE']._serialized_end=294
  _globals['_CARSCATALOGSERVICE']._serialized_start=296
  _globals['_CARSCATALOGSERVICE']._serialized_end=374
# @@protoc_insertion_point(module_scope)
